allow multi-key in tone example
adafruit/Adafruit_CircuitPython_MacroPad pull request #17
Opened 2021-08-01 01:04 UTC by RufusVS

This simple change allows a second key to be pressed even before a previous key is released.

2021-08-05 17:23 UTC, kattni requested changes
Hello! Thanks for your contribution! 

This example is already in a guide and is designed to show the simplest use of these features of this library. If you would like to submit this as a separate example called perhaps `macropad_tone_keypad_multi_key.py` or something similar, I would be happy to include it. If you do this, please include the licensing at the top as it is in this example, with your name instead. Thanks!

2021-08-05 20:26 UTC, RufusVS commented
Hi Kattni.   Thanks for checking out my submission.  I only made the change because I noticed when I played around with my pad I had to fully release a key before pressing another one.   Tickling the keys "quickly" didn't sound right.   But I don't think this change is significant enough to merit another example program.  I might work on more significant submissions when the sound output issues in the library are fixed (following the forums)

2021-08-06 21:12 UTC, kattni commented
@RufusVS I sincerely hope you do submit something when you're ready. Thanks so much for your understanding!

2021-08-06 21:12 UTC, closed without merging

2021-08-07 17:18 UTC, RufusVS commented
I leave my macropad on mydesk and I periodically fiddle with the keys, and the lights and sounds are far more satisfying with the changes I made.  But as a learning tool, I suppose the simpler is better.  You should try my changes and just pound and twiddle the keys and see what I mean.